# Generated by Django 4.2.7 on 2023-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0002_word_lesson_worlds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='worlds',
        ),
        migrations.AddField(
            model_name='lesson',
            name='worlds',
            field=models.ManyToManyField(related_name='lessons', to='translater.word'),
        ),
    ]
